# Generated by Django 3.0.7 on 2022-06-15 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220615_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Teams', 'verbose_name_plural': 'Team'},
        ),
    ]
