# Generated by Django 3.0.7 on 2022-06-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220615_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
